use_frameworks!
pod 'pop'
pod 'AFNetworking'
pod 'FLAnimatedImage', '~> 1.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'ReactiveCocoa'
pod 'MJRefresh'
pod 'MJExtension'
pod 'NYXImagesKit', '2.3'
